version: '3'
services:
  node:
    build: .
    command: npm run start
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: adminwinery
      POSTGRES_PASSWORD: adminpasswinery
      POSTGRES_DB: winery_crud
    ports:
      - "5432:5432"
