version: '3'
services:
  node:
    build: .
    command: npm run start
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_NAME=winery_crud
      - DB_PASSWORD=adminWinery
      - DB_USER=postgresWinery
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=adminWinery
      - POSTGRES_USER=postgresWinery
      - POSTGRES_DB=winery_crud
    volumes:
      - /path/to/db:/var/lib/postgresql/data
