version: '3.9'

services:
  app:
    build: .
    container_name: vineyard_api
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    container_name: database_vineyard_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=adminvineyard
      - POSTGRES_PASSWORD=vineyardpass
      - POSTGRES_DB=winery_crud
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
