version: '3'
services:
  node:
    build: .
    command: "yarn start"
    working_dir: /home/node/app
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: winery_crud
    expose:
      - "3000"
    ports:
      - "3000:3000"
