version: '3'

services:
  app:
    build: .
    container_name: winery_api
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    container_name: database_winery_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=phmorais
      - POSTGRES_PASSWORD=winerydatapass
      - POSTGRES_DB=winery_database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
